# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{textmagic}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Vladimír Bobeš Tužinský"]
  s.date = %q{2010-06-01}
  s.default_executable = %q{tm}
  s.description = %q{
      textmagic is a Ruby interface to the TextMagic's Bulk SMS Gateway.
      It can be used to easily integrate SMS features into your application.
      It supports sending messages, receiving replies and more.
      You need to have a valid TextMagic account to use this gem. You can get one at http://www.textmagic.com.
    }
  s.email = %q{vladimir.tuzinsky@gmail.com}
  s.executables = ["tm"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "History.txt",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "bin/tm",
     "lib/api.rb",
     "lib/charset.rb",
     "lib/error.rb",
     "lib/executor.rb",
     "lib/response.rb",
     "lib/textmagic.rb",
     "lib/validation.rb",
     "test/test_api.rb",
     "test/test_charset.rb",
     "test/test_error.rb",
     "test/test_executor.rb",
     "test/test_helper.rb",
     "test/test_response.rb",
     "test/test_validation.rb",
     "textmagic.gemspec"
  ]
  s.homepage = %q{http://github.com/bobes/textmagic}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{textmagic}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby interface to the TextMagic's Bulk SMS Gateway}
  s.test_files = [
    "test/test_api.rb",
     "test/test_charset.rb",
     "test/test_error.rb",
     "test/test_executor.rb",
     "test/test_helper.rb",
     "test/test_response.rb",
     "test/test_validation.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0.5.2"])
      s.add_development_dependency(%q<mocha>, [">= 0.9.8"])
      s.add_development_dependency(%q<shoulda>, [">= 2.10.3"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.2.8"])
      s.add_development_dependency(%q<mcmire-matchy>, [">= 0.5.2"])
    else
      s.add_dependency(%q<httparty>, [">= 0.5.2"])
      s.add_dependency(%q<mocha>, [">= 0.9.8"])
      s.add_dependency(%q<shoulda>, [">= 2.10.3"])
      s.add_dependency(%q<fakeweb>, [">= 1.2.8"])
      s.add_dependency(%q<mcmire-matchy>, [">= 0.5.2"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0.5.2"])
    s.add_dependency(%q<mocha>, [">= 0.9.8"])
    s.add_dependency(%q<shoulda>, [">= 2.10.3"])
    s.add_dependency(%q<fakeweb>, [">= 1.2.8"])
    s.add_dependency(%q<mcmire-matchy>, [">= 0.5.2"])
  end
end

